<section class="section" id="head">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
				<h2>Editar usuarios</h2>
				<form action="<?php echo APP_URL.'usuarios/edit';?>" method="POST" accept-charset="utf-8">

					<input type="hidden" name="id" value="<?php echo $this->usuario['id'];?>">
					<p>Email <input type="text" name="email" value="<?php echo $this->usuario['email'];?>"></p>
					<p>Username<input type="text" name="username" value="<?php echo $this->usuario['username'];?>"></p>
					<p>Password<input type="password" name="password" value="<?php echo $this->usuario['password'];?>"></p>
					<p>Status <input type="range" name="status" value="<?php echo $this->usuario['status'];?>"></p>
					<p><input type="submit"></p>
				</form>
			</div>
		</div>
	</div>
</section>
