<section class="section" id="head">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
        <h1><?php echo $this->titulo;?></h1>
         <a href="<?php echo APP_URL."usuarios/add"; ?>">Agregar Usuarios</a>
        <table border="1" class="col-md-60 col-lg-30 col-md-offset-1 col-lg-offset-1 text-center">
        	<tr>
        		<th>ID</th>
        		<th>Email</th>
        		<th>Username</th>
        		<th>Password</th>
        		<th>Status</th>
        		<th>Opcion</th>
        	</tr>
        <?php foreach ($this->usuarios as $usuario): ?>
        	<tr>
        		  <td><?php echo $usuario['id'];?></td>
        		  <td><?php echo $usuario['email'];?></td>
        			<td><?php echo $usuario['username'];?></td>
        			<td><?php echo $usuario['password'];?></td>
        			<td><?php echo $usuario['status'];?></td>
        		<td>
        			<a href="<?php echo APP_URL; ?>usuarios/edit/<?php echo $usuario['id']; ?>">Editar</a> |
        			<a href="<?php echo APP_URL; ?>usuarios/delete/<?php echo $usuario['id']; ?>"> Eliminar</a>
        	   </td>
        	</tr>
        <?php endforeach; ?>
        </table>
      </div>
    </div>
  </div>
</section>
