

<section class="section" id="head">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
				    <h2>Agregar categoria</h2>


				 <form action="<?php echo APP_URL.'categorias/add'; ?>" method="POST" accept-charset="utf-8">
					<p>Nombre <input type="text" name="nombre" value=""></p>
					<p><input type="submit">Guardar</p>
				</form>
			</div>
		</div>
	</div>
</section>
