<section class="section" id="head">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
				<h2>Editar categoria</h2>

				<form action="<?php echo APP_URL.'categorias/edit'; ?>" method="POST" accept-charset="utf-8">
                    <input type="hidden" name="id" value="<?php echo $this->categoria['id'];?>">
					<p>Nombre <input type="text" name="nombre" value="<?php echo $this->categoria['nombre'];?>"></p>
					<p><input type="submit"></p>
				</form>
			</div>
		</div>
	</div>
</section>
