<section class="section" id="head">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
        <h1><?php echo $this->titulo;?></h1>
        <a href="<?php echo APP_URL."tareas/add";?>">Agregar Tareas</a>
        <table border="1" class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
          <tr>
            <th>ID</th>
		        <th>Nombre</th>
		        <th>categoria</th>
		        <th>Fecha</th>
		        <th>Prioridad</th>
	             <th>Status</th>
		        <th>Acción</th>
	        </tr>
          <?php foreach ($this->tareas as $tarea): ?>
            <tr>

		            <td><?php echo $tarea[0]; ?></td>
					<td><?php echo $tarea[2]; ?></td>
					<td><?php echo $tarea[7]; ?></td>
					<td><?php echo $tarea["fecha"]; ?></td>
					<td><?php echo $tarea["prioridad"]; ?></td>
					<td><?php echo $tarea["status"]; ?></td>
	            <td> <a href="<?php echo APP_URL."tareas/edit/".$tarea['id'];?>">Editar</a>|<a href="<?php echo APP_URL."tareas/delete/".$tarea['id'];?>">Eliminar</a></td>
            </tr> <?php endforeach; ?>
          </table>
        </div>
      </div>
    </div>
  </section>
